### ISSUE TITLE
Source Code?

### ISSUE THREAD

**Issue by GibreelAbdullah** [GreenTechBd/Al-Quran-Tafsir-by-Word-#3]
Assalamualaikum,

Not an issue.

Jazakallahu Khair for your useful apps. I wanted to know if the project is open source and if I can get access to it?

Gibreel Abdullah

**Comment by Ysajid** [comment]
Walaikumus salam wa rahmatullah.

This project is not currently open-sourced. But let us know if you want to contribute to the project, have any suggestions or any help you may need if you are doing your own Islamic project.

**Comment by GibreelAbdullah** [comment]
Yes, I would like to contribute. I did stumble upon the gitlab repo, but that is also private.

I have recently started app development and have published a couple on the play store (soon on app store as well InShaAllah).

**Comment by vipafattal** [comment]
It happens that we're working on supporting more Arabic translation in our fully free Android App 'Mushaf for Android'.

Thanks for your efforts for that blessed project, we're working on expanding Arabic translation in Mushaf for Android ([Github](https://github.com/vipafattal/Mushaf), [play](https://play.google.com/store/apps/details?id=com.brilliancesoft.mushaf)).

Since Musahf for Android is based on [alquran.cloud](https://alquran.cloud/api) API, we're working on adding them there first so they become be available in the mobile app.

So is it possible to help us support more Arabic translations of the app?
